- name: Create purging cron jobs
  sudo: yes
  cron:
    name: "{{ item.name }}"
    special_time: daily
    job: "find {{ item.dir }} -type f -maxdepth 1 -mtime +{{ item.max_age }} -delete"
    user: root
    cron_file: purge_celery_cache_files
  with_items:
    - {name: 'Purge old temp files', dir: "/tmp", max_age: 2}
  tags:
    - commcarehq
    - celery_hq
