- name: monit config
  become: yes
  template:
    src: "monitrc.j2"
    dest: "/etc/monit/monitrc"
    group: root
    owner: root
    mode: 0600
  tags: monit

- name: start monit
  become: yes
  service: name="monit" state=started enabled=yes
  tags: monit
