- name: "Custom host file lines"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{item}}" state=present
  with_items: "{{ etc_host_lines }}"
  tags:
    - etc_hosts

- name: "Add host file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{item}}" state=present
  with_items:
    - "{{ lookup('dig', inventory_hostname, wantlist=True)[0] }}\t\t{{ inventory_hostname }}"
  tags:
    - etc_hosts
  when: not inventory_hostname|ipaddr

- name: "Remove lines from hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{item}}" state=absent
  with_items: "{{ etc_host_lines_removed }}"
  tags:
    - etc_hosts

# For 12.04 Ubuntu, upgrade OpenSSL version
- name: "Install libssl1.0.0"
  apt: name="libssl1.0.0" state=present
  tags:
    - upgrade_openssl


- name: Hard file limits
  sudo: yes
  pam_limits:
    domain: "{{ item }}"
    limit_type: hard
    limit_item: nofile
    value: "{{ nofile_limit|default(4096) }}"
  tags:
    - nofile_limits
  with_items:
    - '*'
    - 'root'


- name: Soft file limits
  sudo: yes
  pam_limits:
    domain: "{{ item }}"
    limit_type: soft
    limit_item: nofile
    value: "{{ nofile_limit|default(4096) }}"
  tags:
    - nofile_limits
  with_items:
    - '*'
    - 'root'

- name: Ensure pam_limits.so
  lineinfile:
    dest: /etc/pam.d/common-session
    state: present
    regexp: "^session required pam_limits.so"
    line: "session required pam_limits.so"
  tags:
    - nofile_limits

- name: set timezone to Etc/UTC
  become: yes
  timezone:
    name: Etc/UTC
  tags:
    - timezone

- name: "Sets hostname"
  become: yes
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined
  tags:
    - hostname

- name: "Sets /etc/hosts"
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }} '
    line: '{{ ansible_default_ipv4.address }} {{ hostname }}.{{ internal_domain_name }} {{ hostname }}'
  when: hostname is defined and internal_domain_name is defined
  tags:
    - hostname

- name: "Checks if anti-virus service exists (nails)"
  stat: path=/etc/init.d/nails
  register: antivirus
  tags:
    - antivirus
    - after-reboot

- name: "Disables anti-virus (nails)"
  become: yes
  service:
    name: nails
    state: stopped
    enabled: no
  when: antivirus.stat.exists
  tags:
    - antivirus
    - after-reboot

- name: "Checks if other anti-virus services exists (cma)"
  stat: path=/etc/init.d/cma
  register: antivirus_cma
  tags:
    - antivirus
    - after-reboot

- name: "Disables other anti-virus services (cma)"
  become: yes
  service:
    name: cma
    state: stopped
    enabled: no
  when: antivirus_cma.stat.exists
  tags:
    - antivirus
    - after-reboot

- name: "Checks if other anti-virus services exists (ma)"
  stat: path=/etc/init.d/ma
  register: antivirus_ma
  tags:
    - antivirus
    - after-reboot

- name: "Disables other anti-virus services (ma)"
  become: yes
  service:
    name: ma
    state: stopped
    enabled: no
  when: antivirus_ma.stat.exists
  tags:
    - antivirus
    - after-reboot

- include: antivirus.yml
