---
# common tasks needed for interactions with aws
- name: Ensure VPC
  ec2_vpc:
    state: present
    wait: yes
    cidr_block: 10.0.0.0/16
    resource_tags: { "Name": "Dimagi Demo", "Environment": "Demonstration" }
    region: "{{ region }}"
    subnets:
      - cidr: 10.0.1.0/24
        az: "{{ region }}a"
        resource_tags: { "Name": "Dimagi Demo", "Environment": "Demonstration", "Tier": "Webhosts"}
      - cidr: 10.0.2.0/24
        az: "{{ region }}b"
        resource_tags: { "Name": "Dimagi Demo", "Environment": "Demonstration", "Tier": "DB"}
      - cidr: 10.0.3.0/24
        az: "{{ region }}c"
        resource_tags: { "Name": "Dimagi Demo", "Environment": "Demonstration", "Tier": "DB"}
  register: vpc

- name: Group subnets by tier
  set_fact:
    grouped_vpc_subnets: "{{ vpc.subnets|dictby('resource_tags.Tier') }}"

- debug: var=grouped_vpc_subnets

- name: Ensure security groups
  ec2_group:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules: "{{ item.value.rules | default({}) }}"
    rules_egress: "{{ item.value.rules_egress | default({}) }}"
  with_dict: security_groups
  register: sgs

- name: Group security groups by tier
  set_fact:
    grouped_security_groups: "{{ sgs.results|dictby('item.key') }}"

- debug: var=grouped_security_groups
