- name: Install cloudant check
  get_url:
    url: "https://raw.githubusercontent.com/dimagi/datadog-checks/{{ datadog_cloudant_version }}/cloudant/cloudant.py"
    dest: /etc/dd-agent/checks.d/cloudant.py
    sha256sum: "{{ datadog_cloudant_sha256sum }}"
    force: yes
  notify: restart datadog
  when: datadog_integration_cloudant

- name: Install celery check
  get_url:
    url: "https://raw.githubusercontent.com/dimagi/datadog-checks/{{ datadog_celery_version }}/celery/celery.py"
    dest: /etc/dd-agent/checks.d/celery.py
    sha256sum: "{{ datadog_celery_sha256sum }}"
    force: yes
  notify: restart datadog
  run_once: true
  when: inventory_hostname == groups.celery[0]

- name: add datadog integration configs
  template: src={{ item.split('_', 2)[-1] }}.yaml.j2 dest=/etc/dd-agent/conf.d/{{ item.split('_', 2)[-1] }}.yaml
  notify: restart datadog
  tags:
    - datadog_integrations
  when: item
  with_items:
    - datadog_integration_elastic
    - datadog_integration_gunicorn
    - datadog_integration_kafka
    - datadog_integration_kafka_consumer
    - datadog_integration_nginx
    - datadog_integration_pgbouncer
    - datadog_integration_postgres
    - datadog_integration_rabbitmq
    - datadog_integration_redisdb
    - datadog_integration_riak
    - datadog_integration_riakcs
    - datadog_integration_zk
