---
- name: start nginx
  sudo: yes
  service: name=nginx state=start

- name: restart nginx
  sudo: yes
  service: name=nginx state=restarted

- name: reload nginx
  sudo: yes
  service: name=nginx state=reloaded

- name: stop nginx
  sudo: yes
  service: name=nginx state=stopped
