cchq_home: /home/{{ cchq_user }}
www_dir: "{{ cchq_home }}/www"
www_home: "{{ www_dir }}/{{ deploy_env }}"
code_home: "{{ www_home }}/current"
log_home: "{{ www_home }}/log"
service_home: "{{ code_home }}/services"
virtualenv_home: "{{ code_home }}/python_env"
encrypted_root: "/opt/data"

shared_drive_enabled: true  # overridden in ../config/$ENV/$ENV.yml
shared_dir_gid: 1500  # This GID cannot already be allocated
shared_dir_name: "shared_data{{ '_' ~ deploy_env if deploy_env != 'production' else '' }}"
shared_data_dir: "/opt/{{ shared_dir_name }}"
shared_mount_dir: "/mnt/{{ shared_dir_name }}"
transfer_payload_dir_name: "transfer_payloads"
restore_payload_dir_name: "restore_payloads"
shared_temp_dir_name: "temp"
public_site_path: /opt/commcare-hq-public/site/output
commtrack_public_site_path: /opt/commtrack-static/site/output/
cchq_user: cchq
dev_group: dev

django_port: 9010
riakcs_port: 8080
riakcs_control: "{{ groups.get('riakcs')[0] | default('riakcs-is-disabled') }}"
riak_port: 8087
riak_data_dir: "{{ encrypted_root }}/riak"
stanchion_port: 8085
stanchion_data_dir: "{{ encrypted_root }}/stanchion"

# commcare-hq connects to an S3-compatible service, which is Riak CS
s3_blob_db_enabled: "{{ 'true' if groups.get('riakcs') else '' }}"
s3_blob_db_url: "http://{{ groups['proxy'][0] }}:{{ riakcs_port }}"
s3_blob_db_access_key: "{{ hostvars[riakcs_control]['riak_key'] if s3_blob_db_enabled else '' }}"
s3_blob_db_secret_key: "{{ hostvars[riakcs_control]['riak_secret'] if s3_blob_db_enabled else '' }}"

newrelic_agents_pgbouncer: False
newrelic_agents_postgresql: False
newrelic_agents_redis: False
newrelic_agents_rabbitmq: False
newrelic_agents_elastic: False
newrelic_agents_nginx: False
newrelic_agents_apache: False
