cchq_home: /home/{{ cchq_user }}
www_dir: "{{ cchq_home }}/www"
www_home: "{{ www_dir }}/{{ deploy_env }}"
code_home: "{{ www_home }}/code_root"
preindex_home: "{{ www_home }}/code_root_preindex"
log_home: "{{ www_home }}/log"
service_home: "{{ cchq_home }}/services"
virtualenv_home: "{{ www_home }}/python_env"
virtualenv_preindex_home: "{{ www_home }}/python_env_preindex"
shared_mount_dir: "/mnt/shared_data"
restore_payload_dir: "{{ shared_mount_dir }}/restore_payloads"
public_site_path: /opt/commcare-hq-public/site/output

cchq_user: cchq
dev_group: dev

django_port: 9010
