cchq_home: /home/{{ cchq_user }}
www_dir: "{{ cchq_home }}/www"
www_home: "{{ www_dir }}/{{ deploy_env }}"
code_home: "{{ www_home }}/current"
log_home: "{{ www_home }}/log"
service_home: "{{ code_home }}/services"
virtualenv_home: "{{ code_home }}/python_env"
encrypted_root: "/opt/data"

shared_drive_enabled: true  # overridden in ../config/$ENV/$ENV.yml
shared_dir_gid: 1500  # This GID cannot already be allocated
shared_dir_name: "shared{{ '_' ~ deploy_env if deploy_env != 'production' else '' }}"
shared_data_dir: "/opt/{{ shared_dir_name }}"
shared_mount_dir: "/mnt/{{ shared_dir_name }}"
is_monolith: '{{ groups["all"]|length == 1 }}'
transfer_payload_dir_name: "transfer_payloads"
restore_payload_dir_name: "restore_payloads"
shared_temp_dir_name: "temp"
public_site_path: /opt/commcare-hq-public/site/output
commtrack_public_site_path: /opt/commtrack-static/site/output/
cchq_user: cchq
dev_group: dimagidev
dev_users:
  present:
    - biyeun
    - brudolph
    - cellowitz
    - ctsims
    - czue
    - dmiller
    - droberts
    - esoergel
    - frener
    - gcapalbo
    - jemord
    - jschweers
    - mkangia
    - ncarnahan
    - npellegrino
    - nhooper
    - skelly
    - sravfeyn
    - wpride
    - cchq
    - lwyszomirski
  absent:
    - preseed
    - twymer
    - tsheffels
    - dmyung
    - jenkins_slave

django_port: 9010
riakcs_port: 8080
riakcs_control: "{{ groups.get('riakcs')[0] | default('riakcs-is-disabled') }}"
riak_port: 8087
riak_data_dir: "{{ encrypted_root }}/riak"
stanchion_port: 8085
stanchion_data_dir: "{{ encrypted_root }}/stanchion"
zookeeper_client_port: 2181
formplayer_port: 8181

# commcare-hq connects to an S3-compatible service, which is Riak CS
s3_blob_db_enabled: "{{ 'true' if groups.get('riakcs') else '' }}"
s3_blob_db_url: "http://{{ groups['proxy'][0] }}:{{ riakcs_port }}"

# To use these vars without deploying the riak control machine
# add riakcs_s3_access_key and riakcs_s3_secret_key to the ansible secret config directory
s3_blob_db_access_key: "{{ riakcs_s3_access_key if riakcs_s3_access_key is defined else (hostvars[riakcs_control]['riak_key'] if s3_blob_db_enabled else '') }}"
s3_blob_db_secret_key:  "{{ riakcs_s3_secret_key if riakcs_s3_secret_key is defined else (hostvars[riakcs_control]['riak_secret'] if s3_blob_db_enabled else '') }}"

datadog_integration_celery: false
datadog_integration_cloudant: false
datadog_integration_elastic: false
datadog_integration_gunicorn: false
datadog_integration_kafka: false
datadog_integration_kafka_consumer: false
datadog_integration_nginx: false
datadog_integration_pgbouncer: false
datadog_integration_postgres: false
datadog_integration_rabbitmq: false
datadog_integration_redisdb: false
datadog_integration_riak: false
datadog_integration_riakcs: false
datadog_integration_zk: false
datadog_integration_jmx: false
