#- name: allow incoming traffic on private interface
#  ufw: rule=allow direction=in interface={{ ufw_private_interface }}
#
#- name: allow ssh traffic from control machine
#  ufw: rule=allow from={{ control_machine_ip }}
#
#- name: default to denying all incoming traffic
#  ufw: policy=deny direction=incoming
#
- name: allow traffic to squid proxy
  ufw: rule=allow direction=out to={{ groups["squid"][0] }} port=3128

- name: allow DNS lookups
  ufw: rule=allow direction=out port=53

- name: allow smtp traffic to email-smtp.us-east-1.amazonaws.com
  ufw: rule=allow direction=out to={{item}} port=25
  with_items:
    - 107.20.142.169
    - 107.21.238.216
    - 107.22.250.234
    - 23.21.89.230
    - 23.21.205.190
    - 50.19.95.232
    - 50.19.224.18
    - 54.243.69.182

- name: default to deny all outgoing traffic
  ufw: policy=deny direction=outgoing

- name: turn on firewall
  ufw: state=enabled
