---
- name: Restart postgres
  sudo: yes
  action: service name=postgresql state=restarted

- name: Reload postgres
  sudo: yes
  action: service name=postgresql state=reloaded

- name: Start pgbouncer
  sudo: yes
  action: service name=pgbouncer state=started

- name: Reload pgbouncer
  sudo: yes
  action: service name=pgbouncer state=reloaded

- name: Run ldconfig
  sudo: yes
  action: command ldconfig
