---
# Send anything from http -> https
nginx_sites:
- server:
   file_name: "{{ deploy_env }}_commcare_static"
   listen: "80"
   server_name: "{{ SITE_HOST }}"
   client_max_body_size: 100m
   proxy_set_header: "Host $http_host"
   locations:
     - name: /
       return: "301 https://$server_name$request_uri"
