---
# Return maintenance page for other hosts
nginx_sites:
- server:
    file_name: "{{ deploy_env }}_maintenance"
    listen: "80"
    server_name: "*.commcarehq.org"
    locations:
      - name: /
        return: 503
