---
nginx_ssl_cert: "{{ icds_nginx_ssl_cert }}"
nginx_ssl_key:  "{{ icds_nginx_ssl_key }}"

nginx_sites:
- server:
   file_name: icds_tableau
   listen: "443 ssl"
   # Move these to a localsetting?
   server_name: icds.commcarehq.org
   proxy_set_headers:
   - "Host $http_host"
   - "X-Forwarded-For $remote_addr"
   - "X-Forwarded-Proto $scheme"
   - "X-Forwarded-Host $host:443"
   locations:
     - name: /
       proxy_pass: http://tableau2.internal.commcarehq.org
       proxy_read_timeout: 120s
     - name: /errors
       alias: "{{ errors_home }}/pages"
