---

- name: Check for valid partition table on block storage device
  sudo: yes
  shell: fdisk -l 2>&1 | grep 'Disk {{ nfs_datavol_device }} doesn.t contain a valid partition table'
  register: partition_check
  changed_when: false
  failed_when: false
  when: nfs_datavol_device is defined

- name: Create partition on block storage volume
  sudo: yes
  shell: echo -e "o\nn\np\n1\n\n\nw" | fdisk {{ nfs_datavol_device }}
  # http://superuser.com/a/739586/86694
  # o - clear in memory partition table
  # n - new partition
  # p - primary partition
  # 1 - partition number 1
  #   - default - start at beginning of disk 
  #   - default - use entire disk
  # w - write the partition table
  when: nfs_datavol_device is defined and partition_check.rc == 0

- name: Format block storage volume
  sudo: yes
  filesystem: fstype=ext4 dev={{ nfs_datavol_device }}
  when: nfs_datavol_device is defined

- name: Mount block storage volume
  sudo: yes
  mount: name={{ shared_data_dir }} src={{ nfs_datavol_device }}1 fstype=ext4 state=mounted opts=defaults,noatime,user
  when: nfs_datavol_device is defined

- name: Check for already mounted encrypted drive
  shell: grep '{{ shared_data_dir }}' /etc/mtab
  register: mtab_contents
  failed_when: false
  changed_when: false

- name: Create shared data dir
  sudo: yes
  file:
    path: "{{ shared_data_dir }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  tags:
    - nfs
    - shared_files

- name: Create shared directories
  sudo: yes
  file:
    path: "{{ item }}"
    owner: "nobody"
    group: "{{ shared_dir_gid }}"
    mode: "u=rwx,g=rwx,o=r"
    state: directory
  with_items:
    - "{{ restore_payload_dir_host }}"
    - "{{ transfer_payload_dir_host }}"
    - "{{ shared_temp_dir_host }}"
  tags:
    - shared_files

- name: Create purging cron jobs
  sudo: yes
  cron:
    name: "{{ item.name }}"
    special_time: daily
    job: "find {{ item.dir }} -type f -maxdepth 1 -mtime +{{ item.max_age }} -delete"
    user: root
    cron_file: purge_cache_files
  with_items:
    - {name: 'Purge old restore files', dir: "{{ restore_payload_dir_host }}", max_age: 2}
    - {name: 'Purge old transfer files', dir: "{{ transfer_payload_dir_host }}", max_age: 2}
    - {name: 'Purge old temp files', dir: "{{ shared_temp_dir_host }}", max_age: 1}
  tags:
    - shared_files

- name: Add shared dir to exports
  sudo: yes
  when: shared_drive_enabled
  lineinfile:
    dest: /etc/exports
    line: "{{ shared_data_dir }} {{ item }}(rw,sync,all_squash,no_subtree_check,anongid={{ shared_dir_gid }})"
    regexp: "^{{ shared_data_dir }} {{ item }}"
    state: present
  with_flattened:
    - groups.webworkers
    - groups.proxy
    - groups.celery
    - groups.pillowtop
    - groups.shared_dir_host
  tags:
    - nfs

- name: Export directories
  sudo: yes
  when: shared_drive_enabled
  command: "exportfs -a"
  tags:
    - nfs
