---
- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Install nginx
  sudo: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items: nginx_ubuntu_pkg=1.6.2
  when: nginx_install == True

- name: Create nginx http user
  sudo: yes
  user: name={{ nginx_user }} createhome=no password=no state=present groups="{{ cchq_user }}"
  when: nginx_install == True

- name: Create nginx logfile home
  sudo: yes
  file: path={{ log_home }} owner={{ cchq_user }} group={{ cchq_user }} mode=0770 state=directory
  when: nginx_install == True

- name: Create static files home
  sudo: yes
  file: path={{ nginx_static_home }} owner={{ cchq_user }} group={{ cchq_user }} mode=0755 state=directory
  when: nginx_install == True

- name: Copy the nginx configuration file
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Copy the nginx default configuration file
  sudo: yes
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Copy the nginx default site configuration file
  sudo: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: Create the link for site enabled specific configurations
  sudo: yes
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default
