---
- hosts: squid
  vars:
    squid_acls:
      - {name: monolith, type: src, argument: 10.209.162.131}
    squid_http_access_allow_clients:
      - localhost
      - monolith
  roles:
    - kbrebanov.squid

- name: configure http_proxy for package managers
  hosts: monolith
  roles:
    - http_proxy
