---
- name: Common Database Machine Setup
  hosts:
    - postgresql
    - couchdb
    - redis
    - elasticsearch
    - rabbitmq
    - zookeeper
  sudo: yes
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}
    - {role: backups, tags: 'backups'}

- name: Postgresql
  hosts: postgresql
  sudo: yes
  roles:
    - {role: postgresql, tags: 'postgresql'}

- name: Couchdb
  hosts: couchdb
  sudo: yes
  roles:
    - {role: couchdb, tags: 'couchdb'}

- name: Redis
  hosts: redis
  sudo: yes
  roles:
    - {role: redis, tags: 'redis'}

- name: Elasticsearch
  hosts: elasticsearch
  sudo: yes
  roles:
    - {role: elasticsearch, tags: 'elasticsearch'}

- name: Redis Monitoring
  hosts: redis
  sudo: yes
  roles:
    - {role: redis_monitoring, tags: 'redis'}

- name: RabbitMQ
  hosts: rabbitmq
  sudo: yes
  roles:
    - {role: rabbitmq, tags: 'rabbitmq'}

- name: Zookeeper
  hosts: zookeeper
  sudo: yes
  roles:
    - {role: zookeeper, tags: 'zookeeper'}

- name: Kafka
  hosts: kafka
  sudo: yes
  roles:
    - {role: kafka, tags: 'kafka'}

- name: Newrelic Plugin Agent for DB
  hosts:
    - postgresql
    - redis
    - rabbitmq
  tasks:
    - include: roles/newrelic/tasks/plugin-agent.yml
      when: run_newrelic_plugin_agent
  tags:
    - newrelic-plugin-agent

- include: deploy_riakcs.yml

# Note other machines also have java installed, but are initiated through the meta task
- name: Java
  sudo: True
  hosts:
    - celery
  roles:
    - {role: java, tags: java}

- name: Rackspace Cloud Backup Agent
  sudo: yes
  hosts:
    - rackspace_cloud_backup
  roles:
    - {role: Rackspace_Automation.cloud-backup-agent, tags: 'rackspace-backup'}
