- name: "Install postfix"
  hosts: all
  sudo: yes
  tasks:
    - debconf: name=postfix question="postfix/main_mailer_type" value="Internet Site" vtype="string"
    - apt: name=postfix state=present force=yes

- name: "mail relay deploy"
  hosts: mailrelay
  sudo: yes
  tasks:
    - name: "sets our relayhost"
      lineinfile:
        dest: /etc/postfix/main.cf
        regexp: '^relayhost ='
        line: "relayhost = {{ parent_mailrelay }}"
      when: groups['mailrelay'] is defined and parent_mailrelay is defined
    - name: "grants relay access"
      lineinfile:
        dest: /etc/postfix/main.cf
        regexp: '^mynetworks ='
        line: "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 {{ groups['all']|join('/32 ') }}"
      when: groups['mailrelay'] is defined and parent_mailrelay is defined

- name: "mail relay clients deploy"
  hosts: all:!mailrelay
  sudo: yes
  tasks:
    - name: "sets external relayhost"
      lineinfile:
        dest: /etc/postfix/main.cf
        regexp: '^relayhost ='
        line: "relayhost = {{ groups['mailrelay'][0] }}"
      when: groups['mailrelay'] is defined
