---
# roles/postgresql/tasks/main.yml

- name: Add PosgreSQL apt repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename}}-pgdg main' state=present
  register: add_postgresql_repo
  tags:
    - pgbouncer

- name: Add PosgreSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  tags:
    - pgbouncer

- name: Update package list
  apt: update_cache=yes
  when: add_postgresql_repo|changed
  tags:
    - pgbouncer

- name: Install PostgreSQL & dependencies
  apt: name={{ item }} state=present
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-{{ postgresql_version }}-plproxy
    - postgresql-contrib-{{ postgresql_version }}
    - postgresql-server-dev-{{ postgresql_version }}
    - python-docutils  # required for building pghashlib
    - libpq-dev
    - python-psycopg2
    - unzip
  when:
    pg_install == True

- name: Check for original postgresql directory
  stat: path="{{ postgresql_dir_original_path }}/{{ postgresql_version }}"
  register: orig_path
  when: pg_install == True

- name: Make new postgresql directory
  sudo: yes
  file:
    path: '{{ postgresql_dir_path }}'
    owner: postgres
    group: postgres
    mode: 0755
    state: directory
  when: pg_install == True

- name: Check for new postgresql directory
  stat: path="{{ postgresql_dir_path }}/{{ postgresql_version }}"
  register: new_path
  when: pg_install == True

- name: Assert postgresql directory shows up in exactly one place
  fail: msg="postgresl directory must either be {{ postgresql_dir_path }} or {{ postgresql_dir_original_path }} (and not both)"
  when: >
    pg_install == True and
    ((orig_path.stat.exists and new_path.stat.exists) or (not orig_path.stat.exists and not new_path.stat.exists))

- name: Move postgres to encrypted drive
  command: "mv {{ postgresql_dir_original_path }}/{{ postgresql_version }} {{ postgresql_dir_path }}/{{ postgresql_version }}"
  when: pg_install == True and orig_path.stat.exists

- name: generate en_US.UTF-8 locale
  locale_gen: name='en_US.UTF-8' state=present
  when:
    pg_install == True

- name: PostgreSQL app configuration
  sudo_user: postgres
  template: src=postgresql.conf.j2 dest={{ postgresql_config_home }}/postgresql.conf
  notify: Restart postgres

- name: PostgreSQL access configuration
  sudo_user: postgres
  template: src=pg_hba.conf.j2 dest={{ postgresql_config_home }}/pg_hba.conf
  notify: Reload postgres

- name: start postgresql
  sudo_user: postgres
  service: name=postgresql state=started

- name: Create PostgreSQL users
  sudo_user: postgres
  postgresql_user:
    name: "{{ localsettings.PG_DATABASE_USER }}"
    password: "{{ localsettings.PG_DATABASE_PASSWORD }}"
    role_attr_flags: CREATEDB
    state: present
    port: "{{ postgresql_port }}"
  when:
    pg_install == True

- name: Create PostgreSQL devreadonly user
  sudo_user: postgres
  postgresql_user:
    name: postgres_users.devreadonly.username
    password: postgres_users.devreadonly.password
    role_attr_flags: LOGIN
    encrypted: yes
    state: present
    port: "{{ postgresql_port }}"
  when:
    pg_install == True

- name: Grant Read Access for devreadonly user
  sudo_user: postgres
  postgresql_privs:
    database: "{{ item.name }}"
    login: "{{ localsettings.PG_DATABASE_USER }}"
    password: "{{ localsettings.PG_DATABASE_PASSWORD }}"
    role: postgres_users.devreadonly.username
    privs: SELECT
  with_items: "{{ postgresql_dbs }}"
  when: pg_install == True

- name: Create PostgreSQL databases
  sudo_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    state: present
    port: "{{ postgresql_port }}"
    owner: "{{ localsettings.PG_DATABASE_USER }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
  with_items: "{{ postgresql_dbs }}"
  when:
    pg_install == True

- name: Install pgbouncer
  apt: name=pgbouncer state=present
  when:
    pg_install == True
  notify: Start pgbouncer
  tags:
    - pgbouncer

- name: pgbouncer configuration
  template: src=pgbouncer.ini.j2 dest={{ pg_bouncer_ini }}
  notify: Reload pgbouncer
  tags:
    - pgbouncer

- name: pgbouncer users
  template: src=pgbouncer.users.j2 dest={{ pg_bouncer_users }}
  notify: Reload pgbouncer
  tags:
    - pgbouncer

- name: pgbouncer defaults
  template: src=pgbouncer.defaults.j2 dest=/etc/default/pgbouncer
  tags:
    - pgbouncer

- name: Download pghashlib
  get_url: url=https://github.com/markokr/pghashlib/archive/master.zip dest=/tmp/pghashlib.zip

- name: Unzip pghashlib
  command: unzip pghashlib.zip
  args:
     chdir: /tmp
     creates: /tmp/pghashlib-master

- name: Install pghashlib
  sudo: yes
  shell: "PG_CONFIG={{postgres_install_dir}}/bin/pg_config make install"
  args:
    chdir: /tmp/pghashlib-master
    creates: "{{postgres_install_dir}}/lib/hashlib.so"
  notify: Run ldconfig
  notify: Restart postgres

- name: Create plproxy extension
  sudo_user: postgres
  shell: "{{postgres_install_dir}}/bin/psql -U postgres -p {{postgresql_port}} {{item.name}} -c 'CREATE EXTENSION IF NOT EXISTS plproxy'"
  when: item.get('django_alias') == 'proxy'
  with_items: postgresql_dbs

- name: Create pghashlib extension
  sudo_user: postgres
  shell: "{{postgres_install_dir}}/bin/psql -U postgres -p {{postgresql_port}} {{item.name}} -c 'CREATE EXTENSION IF NOT EXISTS hashlib'"
  when: item.get('django_alias') == 'proxy'
  with_items: postgresql_dbs

- name: Make plproxy a trusted language
  sudo_user: postgres
  shell: "{{postgres_install_dir}}/bin/psql -U postgres -p {{postgresql_port}} {{item.name}} -c \"UPDATE pg_language SET lanpltrusted = true WHERE lanname = 'plproxy'\""
  when: item.get('django_alias') == 'proxy'
  with_items: postgresql_dbs

- name: Grant usage on plproxy FDW
  sudo_user: postgres
  shell: "{{postgres_install_dir}}/bin/psql -U postgres -p {{postgresql_port}} {{item.name}} -c \"GRANT USAGE on FOREIGN DATA WRAPPER plproxy to {{item.get('user', localsettings.PG_DATABASE_USER)}}\""
  when: item.get('django_alias') == 'proxy'
  with_items: postgresql_dbs

- name: create backup directory
  sudo: yes
  file:
    path: '{{ postgresql_backup_dir }}'
    owner: postgres
    group: postgres
    mode: 0755
    state: directory
  when: backup_postgres

- name: Copy postgres backup script
  sudo: yes
  template:
    src: "create_postgres_dump.sh.j2"
    dest: "/etc/cron.d/create_postgres_dump.sh"
    group: postgres
    owner: postgres
    mode: 0700
    backup: yes
  when: backup_postgres

- name: Create Daily Cron job
  sudo: yes
  cron:
    name: "Backup postgres daily"
    job: "/etc/cron.d/create_postgres_dump.sh daily 7"
    minute: 0
    hour: 0
    weekday: "1,2,3,4,5,6"
    user: postgres
    cron_file: ../crontab
  when: backup_postgres

- name: Create Weekly Cron job
  sudo: yes
  cron:
    name: "Backup postgres weekly"
    job: "/etc/cron.d/create_postgres_dump.sh weekly 28"
    minute: 0
    hour: 0
    weekday: 0
    user: postgres
    cron_file: ../crontab
  when: backup_postgres
